# This is a server config
[server.http]
port = 80
static_path = ""
static_fs = ""

[server.grpc]
port = 9876

# This is a store config
[store.etcd]
endpoints = ["http://127.0.0.1:2379"]
username = ""
password = ""

[store.mysql]
dsn = "root:1234567@tcp(127.0.0.1:3306)/auth?charset=utf8&parseTime=True&loc=%s&readTimeout=10s&timeout=30s"

[store.gorm]
dsn = "root:1234567@tcp(127.0.0.1:3306)/auth?charset=utf8&parseTime=True&loc=Local"
DefaultStringSize = 1234

# This is a client config
[client.kube]
path = "./"

[client.nsq]
admin_addr = "http://127.0.0.1:4171"

# This is a mq config
[pipeline.nsq]
loop_addr = "127.0.0.1:4161"

[pipeline.rabbit]
url = "amqp://guest:guest@127.0.0.1:5672/"

# This is a test cofnig
[people]
name = "jupiter"

[database]
server = "192.168.1.1"
ports = [ 8000, 8001, 8002 ]
connection_max = 5000
enabled = true